//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSalesOrderDetail
    {
        public int SalesOrderID { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public decimal TotalDue { get; set; }
        public short OrderQty { get; set; }
        public int ProductID { get; set; }
    }
}
